# Generated by Django 4.2.3 on 2023-07-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandChoices', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryChoices', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelChoices', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='phonedata',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.categorychoices'),
        ),
        migrations.AlterField(
            model_name='phonedata',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.brandchoices'),
        ),
        migrations.AlterField(
            model_name='phonedata',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.modelchoices'),
        ),
    ]
