# Generated by Django 4.2.3 on 2023-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0002_brandchoices_categorychoices_modelchoices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedata',
            name='price',
            field=models.FloatField(),
        ),
    ]
